routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('page/home');
// });

Route::auth();

Route::group(['middleware'=>'auth'], function(){
	Route::get('/', 'KelasController@index');
	Route::get('kelas', 'KelasController@index');
	Route::get('kelas/add', 'KelasController@create');
	Route::post('kelas/add', 'KelasController@store');

	Route::get('kelas/{id}/edit', 'KelasController@edit');
	Route::patch('kelas/{id}/edit', 'KelasController@update');
	Route::delete('kelas/{id}/delete', 'KelasController@destroy');

	Route::get('siswa', 'SiswaController@index');
	Route::get('siswa/add', 'SiswaController@create');
	Route::post('siswa/add', 'SiswaController@store');

	Route::get('siswa/{nis}/edit', 'SiswaController@edit');
	Route::patch('siswa/{nis}/edit', 'SiswaController@update');
	Route::delete('siswa/{nis}/delete', 'SiswaController@destroy');
});

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    public $primaryKey = 'id_kelas';

    protected $table = 't_kelas';

    protected $fillable = [
    	'nama_kelas', 'jurusan'
    ];
}

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
	public $primaryKey = 'nis';

	protected $table = 't_siswa';

	protected $fillable = [
		'nis', 'nama_lengkap', 'jenis_kelamin', 'alamat', 'no_telp', 'id_kelas', 'foto'
	];

	public function getJenisKelaminDisplayAttribute() {
		if (@$this->attributes['jenis_kelamin'] == 'L') return 'Laki-Laki';
		if (@$this->attributes['jenis_kelamin'] == 'P') return 'Perempuan';
		return '-';
	}

	public function kelas(){
		return $this->hasOne('\App\Kelas', 'id_kelas', 'id_kelas');
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class KelasController extends Controller
{
	public function index(){
		$data['result'] = \App\Kelas::all();
		return view('page/kelas/index')->with($data);
	}

	public function create(){
		return view('page/kelas/form');
	}

	public function store(Request $request){
		$rules = [
			'nama_kelas'	=> 'required|max:100',
			'jurusan'		=> 'required|max:100'
		];
		$this->validate($request, $rules);

		$input = $request->all();
		$status = \App\Kelas::create($input);

		if ($status) return redirect('/')->with('success', 'Data berhasil ditambahkan');
		else return redirect('/')->with('error', 'Data gagal ditambahkan');
	}

	public function edit($id) {
		$data['result'] = \App\Kelas::where('id_kelas', $id)->first();
		return view('page/kelas/form')->with($data);
	}

	public function update(Request $request, $id){
		$rules = [
			'nama_kelas'	=> 'required|max:100',
			'jurusan'		=> 'required|max:100'
		];
		$this->validate($request, $rules);

		$input = $request->all();
		$result = \App\Kelas::where('id_kelas', $id)->first();
		$status = $result->update($input);

		if ($status) return redirect('/')->with('success', 'Data berhasil diubah');
		else return redirect('/')->with('error', 'Data gagal diubah');
	}

	public function destroy(Request $request, $id) {
		$result = \App\Kelas::where('id_kelas', $id)->first();
		$status = $result->delete();

		if ($status) return redirect('/')->with('success', 'Data berhasil dihapus');
		else return redirect('/')->with('error', 'Data gagal dihapus');
	}
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SiswaController extends Controller
{
	public function index(){
		$data['result'] = \App\Siswa::all();
		return view('page/siswa/index')->with($data);
	}

	public function create() {
		return view('page/siswa/form');
	}

	public function store(Request $request){
		$rules = [
			'nis'			=> 'required|unique:t_siswa',
			'nama_lengkap'	=> 'required|max:100',
			'jenis_kelamin'	=> 'required',
			'alamat'		=> 'required',
			'no_telp'		=> 'required',
			'id_kelas'		=> 'required|exists:t_kelas',
			'foto'			=> 'required|mimes:jpeg,png|max:512'

		];
		$this->validate($request, $rules);

		$input = $request->all();

		if ($request->hasFile('foto') && $request->file('foto')->isValid()){
			$filename = $input['nis'] . "." . $request->file('foto')->getClientOriginalExtension();
			$request->file('foto')->move(public_path('/uploads/fotosiswa'),$filename);
			$input['foto'] = $filename;
		}

		$status = \App\Siswa::create($input);

		if ($status) return redirect('siswa')->with('success', 'Data berhasil ditambahkan');
		else return redirect('siswa')->with('error', 'Data gagal ditambahkan');
	}
	public function edit($id) {
		$data['result'] = \App\Siswa::where('nis', $id)->first();
		return view('page/siswa/form')->with($data);
	}

	public function update(Request $request, $id){
		$rules = [
			'nama_lengkap'	=> 'required|max:100',
			'jenis_kelamin'	=> 'required',
			'alamat'		=> 'required',
			'no_telp'		=> 'required',
			'id_kelas'		=> 'required|exists:t_kelas',
			'foto'			=> 'required|mimes:jpeg,png|max:512'
		];
		$this->validate($request, $rules);

		$input = $request->all();
		$result = \App\Siswa::where('nis', $id)->first();
		
		if ($request->hasFile('foto') && $request->file('foto')->isValid()){
			$filename = $input['nis'] . "." . $request->file('foto')->getClientOriginalExtension();
			$request->file('foto')->move(public_path('/uploads/fotosiswa'),$filename);
			$input['foto'] = $filename;
		}

		$status = $result->update($input);

		if ($status) return redirect('siswa')->with('success', 'Data berhasil diubah');
		else return redirect('siswa')->with('error', 'Data gagal diubah');
	}

	public function destroy(Request $request, $id) {
		$result = \App\Siswa::where('nis', $id)->first();
		$status = $result->delete();

		if ($status) return redirect('siswa')->with('success', 'Data berhasil dihapus');
		else return redirect('siswa')->with('error', 'Data gagal dihapus');
	}
}

resources/views/layouts/feedback.blade.php
@if(session('success'))
	<div class="alert alert-success fade in">
		<button type="button" class="close pull-right" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		{!! session('success') !!}
	</div>
@endif

@if(session('error'))
	<div class="alert alert-danger fade in">
		<button class="close pull-right" type="button" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		{!! session('error') !!}
	</div>
@endif

@if (count($errors) > 0)
	<div class="alert alert-danger fade in">
		<button class="close pull-right" type="button" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<p>Perhatian.</p>
		<ul>
			@foreach($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif	

resources/views/layouts/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.8
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
                <
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <div class="control-sidebar-bg"></div>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@yield('title') | Dashboard</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="stylesheet" href="/css/app.css">
</head>
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    @include('layouts.navbar')
    <div class="content-wrapper">
      @yield('content')
    </div>
    @include('layouts.footer')
  </div>
  <script src="/js/app.js"></script>
</body>

resources/views/layouts/navbar.blade.php
<header class="main-header">
<a href="index2.html" class="logo">
    <span class="logo-mini"><b>A</b>LT</span>
    <span class="logo-lg"><b>Admin</b>LTE</span>
</a>
<nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
    <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
        </a>
        <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
            <ul class="menu">
                <li>
                <a href="#">
                    <div class="pull-left">
                    <img src="/images/vendor/admin-lte/dist/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                    Support Team
                    <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                </a>
                </li>
                <li>
                <a href="#">
                    <div class="pull-left">
                    <img src="/images/vendor/admin-lte/dist/user3-128x128.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                    AdminLTE Design Team
                    <small><i class="fa fa-clock-o"></i> 2 hours</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                </a>
                </li>
                <li>
                <a href="#">
                    <div class="pull-left">
                    <img src="/images/vendor/admin-lte/dist/user4-128x128.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                    Developers
                    <small><i class="fa fa-clock-o"></i> Today</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                </a>
                </li>
                <li>
                <a href="#">
                    <div class="pull-left">
                    <img src="/images/vendor/admin-lte/dist/user3-128x128.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                    Sales Department
                    <small><i class="fa fa-clock-o"></i> Yesterday</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                </a>
                </li>
                <li>
                <a href="#">
                    <div class="pull-left">
                    <img src="/images/vendor/admin-lte/dist/user4-128x128.jpg" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                    Reviewers
                    <small><i class="fa fa-clock-o"></i> 2 days</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                </a>
                </li>
            </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
        </ul>
        </li>
        <li class="dropdown notifications-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
        </a>
        <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
            <ul class="menu">
                <li>
                <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                </a>
                </li>
                <li>
                <a href="#">
                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                    page and may cause design problems
                </a>
                </li>
                <li>
                <a href="#">
                    <i class="fa fa-users text-red"></i> 5 new members joined
                </a>
                </li>
                <li>
                <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                </a>
                </li>
                <li>
                <a href="#">
                    <i class="fa fa-user text-red"></i> You changed your username
                </a>
                </li>
            </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
        </ul>
        </li>
        <li class="dropdown tasks-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
        </a>
        <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
            <ul class="menu">
                <li>
                <a href="#">
                    <h3>
                    Design some buttons
                    <small class="pull-right">20%</small>
                    </h3>
                    <div class="progress xs">
                    <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                    </div>
                    </div>
                </a>
                </li>
                <li>
                <a href="#">
                    <h3>
                    Create a nice theme
                    <small class="pull-right">40%</small>
                    </h3>
                    <div class="progress xs">
                    <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">40% Complete</span>
                    </div>
                    </div>
                </a>
                </li>
                <li>
                <a href="#">
                    <h3>
                    Some task I need to do
                    <small class="pull-right">60%</small>
                    </h3>
                    <div class="progress xs">
                    <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">60% Complete</span>
                    </div>
                    </div>
                </a>
                </li>
                <li>
                <a href="#">
                    <h3>
                    Make beautiful transitions
                    <small class="pull-right">80%</small>
                    </h3>
                    <div class="progress xs">
                    <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">80% Complete</span>
                    </div>
                    </div>
                </a>
                </li>
            </ul>
            </li>
            <li class="footer">
            <a href="#">View all tasks</a>
            </li>
        </ul>
        </li>
        <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="/images/vendor/admin-lte/dist/user2-160x160.jpg" class="user-image" alt="User Image">
            <span class="hidden-xs">{{ Auth::user()->name }}</span>
        </a>
        <ul class="dropdown-menu">
            <li class="user-header">
            <img src="/images/vendor/admin-lte/dist/user2-160x160.jpg" class="img-circle" alt="User Image">

            <p>
                {{ Auth::user()->name }}  - Admin
            </p>
            </li>
            <li class="user-body">
            <div class="row">
                <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
                </div>
            </div>
            </li>
            <li class="user-footer">
            <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
            </div>
            <div class="pull-right">
                <form action='{{ url("/logout") }}' method="POST">
                    {{ csrf_field() }}
                    {{ method_field('post') }}
                    <button type="submit" class="btn btn-default btn-flat">Sign out</button>
                </form>
            </div>
            </li>
        </ul>
        </li>
        <li>
        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
    </ul>
    </div>
</nav>
</header>

<aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/images/vendor/admin-lte/dist/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ Auth::user()->name }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="treeview">
          <a href="{{ url('/') }}">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
        <li class="treeview">
          <a href="{{ url('/siswa') }}">
            <i class="fa fa-dashboard"></i> <span>Siswa</span>
          </a>
        </li>
        <li class="treeview">
          <a href="{{ url('/kelas') }}">
            <i class="fa fa-dashboard"></i> <span>Kelas</span>
          </a>
        </li>
      </ul>
    </section>
</aside>

resources/views/page/kelas/form.blade.php
@extends('layouts.main') 
@section('title', 'Management Kelas') 

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {{ empty($result) ? 'Tambah' : 'Edit' }} Data Kelas
        <small>SMK Negeri 4 Bandung</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>Data Kelas</li>
        <li class="active">{{ empty($result) ? 'Tambah' : 'Edit' }} Data Kelas</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      @include('layouts/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <a href="{{ url('/') }}" class="btn bg-purple"><i class="fa fa-chevron-left"></i> Kembali</a>
        </div>
        <div class="box-body">
          <form action="{{ empty($result) ? url('kelas/add') : url("kelas/$result->id_kelas/edit") }}" class="form-horizontal" method="POST">
            {{ csrf_field() }}

            @if (!empty($result))
              {{ method_field('patch') }}
            @endif
            <div class="form-group">
              <label for="" class="control-label col-sm-2">Nama Kelas</label>
              <div class="col-sm-10">
                <input type="text" name="nama_kelas" class="form-control" placeholder="Masukan Nama Kelas"
                value="{{ @$result->nama_kelas }}">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="control-label col-sm-2">Jurusan</label>
              <div class="col-sm-10">
                <input type="text" name="jurusan" class="form-control" placeholder="Masukan Jurusan"
                value="{{ @$result->jurusan }}">
              </div>
            </div>
            
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-2">
                <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Simpan</button>
              </div>
            </div>
          </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

resources/views/page/siswa/index.blade.php
@extends('layouts.main') 
@section('title', 'Management Siswa') 

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Siswa
        <small>SMK Negeri 4 Bandung</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Data Siswa</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      @include('layouts/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <a href="{{ url('siswa/add') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
        </div>
        <div class="box-body">
          <table class="table table-stripped">
            <thead>
              <tr>
                <th>No</th>
                <th>Foto</th>
                <th>Nama Lengkap</th>
                <th>Jenis Kelamin</th>
                <th>Alamat</th>
                <th>No Telp</th>
                <th>Kelas</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              @foreach ($result as $row)
              <tr>
                <td>{{ !empty($i) ? ++$i : $i = 1 }}</td>
                <td>
                  <img src="{{ asset('uploads/fotosiswa/'.@$row->foto) }}" width="80px" class="img">
                </td>
                <td>{{ @$row->nama_lengkap }}</td>
                <td>{{ @$row->jenis_kelamin_display }}</td>
                <td>{{ @$row->alamat }}</td>
                <td>{{ @$row->no_telp }}</td>
                <td>{{ @$row->kelas->nama_kelas }}</td>
                <td>
                  <a href="{{ url("siswa/$row->nis/edit") }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                  <form action="{{ url("siswa/$row->nis/delete") }}"
                  method="POST" style="display: inline;">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection